# Версия Docker Compose
version: '3.8'

# Определяем сервисы
services:
  frontend:
    # Что планируем билдить
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # Порты
    ports:
      - "8501:8501"
    # Монтируем директорию
    volumes:
      - ./frontend:/src/frontend
      - ./pyproject.toml:/src/pyproject.toml
      - ./poetry.lock:/src/poetry.lock
      - poetry_cache:/opt/poetry/cache
      - pip_cache:/opt/pip/cache
    # Переменные окружения
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:8000
    # Рестарт
    restart: unless-stopped
    # Пользовательская сеть
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
      - ./background_removal:/src/background_removal
      - ./pyproject.toml:/src/pyproject.toml
      - ./poetry.lock:/src/poetry.lock
      - poetry_cache:/opt/poetry/cache
      - pip_cache:/opt/pip/cache
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    # Используем образ Postgres
    image: postgres:15-alpine
    # Проброс портов
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: remooovy_postgres_data
  poetry_cache:
    name: remooovy_poetry_cache
  pip_cache:
    name: remooovy_pip_cache

# Определяем сеть, которая создает изолированную среду для контейнеров
networks:
  app-network:
    driver: bridge
